name: First CI Workflow
on:
  - push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - name: Print Message
        run: echo "Hello world"
